#include "direct_mode.h"
#include <dxgi1_2.h>
#include <algorithm>
#include <chrono>
#include <cstdio>

using Microsoft::WRL::ComPtr;
static void debug(const char *s){OutputDebugStringA("SVRT: ");OutputDebugStringA(s);OutputDebugStringA("\n");}
SvrtDirectMode::SvrtDirectMode()=default;
SvrtDirectMode::~SvrtDirectMode(){Stop();}
bool SvrtDirectMode::Start(const std::string &host,uint16_t port,unsigned fps,unsigned bitrate,const std::string &ffmpeg,const std::string &encoder){
  host_=host;port_=port;fps_=fps?fps:60;bitrate_=bitrate?bitrate:35;ffmpeg_=ffmpeg.empty()?"ffmpeg.exe":ffmpeg;encoder_=encoder.empty()?"hevc_nvenc":encoder;
  encoder_failed_=false;UINT flags=D3D11_CREATE_DEVICE_BGRA_SUPPORT;D3D_FEATURE_LEVEL level;HRESULT hr=D3D11CreateDevice(nullptr,D3D_DRIVER_TYPE_HARDWARE,nullptr,flags,nullptr,0,D3D11_SDK_VERSION,&device_,&level,&context_);if(FAILED(hr)){debug("D3D11CreateDevice failed");encoder_failed_=true;return false;}running_=true;worker_=std::thread(&SvrtDirectMode::EncoderThread,this);return true;
}
void SvrtDirectMode::Stop(){if(!running_.exchange(false))return;HANDLE pipe=pipe_;pipe_=INVALID_HANDLE_VALUE;if(pipe!=INVALID_HANDLE_VALUE)CloseHandle(pipe);ready_.notify_all();if(worker_.joinable())worker_.join();CloseEncoder();std::lock_guard<std::mutex> l(mutex_);for(auto &kv:textures_)if(kv.second.shared)CloseHandle(kv.second.shared);textures_.clear();slots_.clear();context_.Reset();device_.Reset();}
void SvrtDirectMode::CreateSwapTextureSet(uint32_t pid,const SwapTextureSetDesc_t *d,SwapTextureSet_t *out){
  *out={};if(!device_||!d)return;D3D11_TEXTURE2D_DESC td{};td.Width=d->nWidth;td.Height=d->nHeight;td.MipLevels=1;td.ArraySize=1;td.Format=(DXGI_FORMAT)d->nFormat;td.SampleDesc.Count=std::max(1u,d->nSampleCount);td.Usage=D3D11_USAGE_DEFAULT;td.BindFlags=D3D11_BIND_RENDER_TARGET|D3D11_BIND_SHADER_RESOURCE;td.MiscFlags=D3D11_RESOURCE_MISC_SHARED_NTHANDLE;
  std::lock_guard<std::mutex> l(mutex_);Texture created[3];uint64_t keys[3]{};for(int i=0;i<3;i++){ComPtr<ID3D11Texture2D> tex;if(FAILED(device_->CreateTexture2D(&td,nullptr,&tex)))goto failed;ComPtr<IDXGIResource1> dxgi;if(FAILED(tex.As(&dxgi)))goto failed;HANDLE h=nullptr;if(FAILED(dxgi->CreateSharedHandle(nullptr,DXGI_SHARED_RESOURCE_READ|DXGI_SHARED_RESOURCE_WRITE,nullptr,&h)))goto failed;keys[i]=(uint64_t)(uintptr_t)h;created[i]=Texture{pid,keys[0],h,tex};}for(int i=0;i<3;i++){created[i].group=keys[0];textures_[keys[i]]=std::move(created[i]);out->rSharedTextureHandles[i]=(vr::SharedTextureHandle_t)keys[i];}out->unTextureFlags=vr::VRSwapTextureFlag_Shared_NTHandle;return;failed:for(auto &t:created)if(t.shared)CloseHandle(t.shared);
}
void SvrtDirectMode::DestroySwapTextureSet(vr::SharedTextureHandle_t h){std::lock_guard<std::mutex> l(mutex_);auto it=textures_.find((uint64_t)h);if(it==textures_.end())return;uint64_t group=it->second.group;for(auto p=textures_.begin();p!=textures_.end();){if(p->second.group==group){CloseHandle(p->second.shared);p=textures_.erase(p);}else ++p;}}
void SvrtDirectMode::DestroyAllSwapTextureSets(uint32_t pid){std::lock_guard<std::mutex> l(mutex_);for(auto p=textures_.begin();p!=textures_.end();){if(p->second.pid==pid){CloseHandle(p->second.shared);p=textures_.erase(p);}else ++p;}}
void SvrtDirectMode::GetNextSwapTextureSetIndex(vr::SharedTextureHandle_t[2],uint32_t (*indices)[2]){next_[0]=(next_[0]+1)%3;next_[1]=(next_[1]+1)%3;(*indices)[0]=next_[0];(*indices)[1]=next_[1];}
void SvrtDirectMode::SubmitLayer(const SubmitLayerPerEye_t (&eyes)[2]){std::lock_guard<std::mutex> l(mutex_);submitted_[0]=eyes[0].hTexture;submitted_[1]=eyes[1].hTexture;}
bool SvrtDirectMode::EnsureSlots(unsigned ew,unsigned h,DXGI_FORMAT fmt){if(width_==ew*2&&height_==h&&!slots_.empty())return true;if(std::any_of(slots_.begin(),slots_.end(),[](const Slot&s){return s.pending;}))return false;width_=ew*2;height_=h;pixel_format_=(fmt==DXGI_FORMAT_R8G8B8A8_UNORM||fmt==DXGI_FORMAT_R8G8B8A8_UNORM_SRGB)?"rgba":"bgra";slots_.clear();D3D11_TEXTURE2D_DESC d{};d.Width=width_;d.Height=height_;d.MipLevels=d.ArraySize=1;d.Format=fmt;d.SampleDesc.Count=1;d.Usage=D3D11_USAGE_STAGING;d.CPUAccessFlags=D3D11_CPU_ACCESS_READ;for(int i=0;i<3;i++){Slot s;if(FAILED(device_->CreateTexture2D(&d,nullptr,&s.staging))){slots_.clear();return false;}slots_.push_back(std::move(s));}return StartEncoder(width_,height_);}
void SvrtDirectMode::Present(vr::SharedTextureHandle_t){std::unique_lock<std::mutex> l(mutex_);auto a=textures_.find((uint64_t)submitted_[0]),b=textures_.find((uint64_t)submitted_[1]);if(a==textures_.end()||b==textures_.end())return;D3D11_TEXTURE2D_DESC d{};a->second.texture->GetDesc(&d);std::lock_guard<std::mutex> dl(d3d_mutex_);if(!EnsureSlots(d.Width,d.Height,d.Format))return;auto slot=std::find_if(slots_.begin(),slots_.end(),[](const Slot&s){return !s.pending;});if(slot==slots_.end())return;D3D11_BOX box{0,0,0,d.Width,d.Height,1};context_->CopySubresourceRegion(slot->staging.Get(),0,0,0,0,a->second.texture.Get(),0,&box);context_->CopySubresourceRegion(slot->staging.Get(),0,d.Width,0,0,b->second.texture.Get(),0,&box);context_->Flush();slot->pending=true;slot->sequence=++sequence_;l.unlock();ready_.notify_one();}
bool SvrtDirectMode::StartEncoder(unsigned w,unsigned h){if(pipe_!=INVALID_HANDLE_VALUE)return true;SECURITY_ATTRIBUTES sa{sizeof(sa),nullptr,TRUE};HANDLE read_pipe=nullptr;if(!CreatePipe(&read_pipe,&pipe_,&sa,1<<20)){encoder_failed_=true;return false;}SetHandleInformation(pipe_,HANDLE_FLAG_INHERIT,0);char cmd[2048];std::snprintf(cmd,sizeof(cmd),"\"%s\" -hide_banner -loglevel warning -fflags nobuffer -f rawvideo -pix_fmt %s -video_size %ux%u -framerate %u -i pipe:0 -an -c:v %s -preset p1 -tune ull -rc cbr -b:v %uM -maxrate %uM -bufsize %uM -g %u -bf 0 -muxdelay 0 -f mpegts \"tcp://%s:%u?tcp_nodelay=1\"",ffmpeg_.c_str(),pixel_format_.c_str(),w,h,fps_,encoder_.c_str(),bitrate_,bitrate_,std::max(1u,bitrate_/2),fps_,host_.c_str(),port_);STARTUPINFOA si{};si.cb=sizeof(si);si.dwFlags=STARTF_USESTDHANDLES;si.hStdInput=read_pipe;si.hStdOutput=GetStdHandle(STD_OUTPUT_HANDLE);si.hStdError=GetStdHandle(STD_ERROR_HANDLE);PROCESS_INFORMATION pi{};BOOL ok=CreateProcessA(nullptr,cmd,nullptr,nullptr,TRUE,CREATE_NO_WINDOW,nullptr,nullptr,&si,&pi);CloseHandle(read_pipe);if(!ok){CloseHandle(pipe_);pipe_=INVALID_HANDLE_VALUE;encoder_failed_=true;debug("failed to launch FFmpeg");return false;}CloseHandle(pi.hThread);process_=pi.hProcess;encoder_failed_=false;return true;}
void SvrtDirectMode::CloseEncoder(){if(pipe_!=INVALID_HANDLE_VALUE){CloseHandle(pipe_);pipe_=INVALID_HANDLE_VALUE;}if(process_){WaitForSingleObject(process_,2000);CloseHandle(process_);process_=nullptr;}}
void SvrtDirectMode::EncoderThread(){while(running_){std::unique_lock<std::mutex> l(mutex_);ready_.wait(l,[this]{return !running_||std::any_of(slots_.begin(),slots_.end(),[](const Slot&s){return s.pending;});});if(!running_)break;auto it=std::find_if(slots_.begin(),slots_.end(),[](const Slot&s){return s.pending;});if(it==slots_.end())continue;Slot *slot=&*it;unsigned w=width_,h=height_;l.unlock();D3D11_MAPPED_SUBRESOURCE map{};bool ok=false;{std::lock_guard<std::mutex> dl(d3d_mutex_);if(process_&&WaitForSingleObject(process_,0)==WAIT_OBJECT_0)encoder_failed_=true;ok=!encoder_failed_&&SUCCEEDED(context_->Map(slot->staging.Get(),0,D3D11_MAP_READ,0,&map));HANDLE pipe=pipe_;if(ok&&pipe!=INVALID_HANDLE_VALUE){for(unsigned y=0;y<h&&ok;y++){DWORD n=0;ok=WriteFile(pipe,(uint8_t*)map.pData+(size_t)y*map.RowPitch,w*4,&n,nullptr)&&n==w*4;}context_->Unmap(slot->staging.Get(),0);}}l.lock();slot->pending=false;if(!ok&&running_){encoder_failed_=true;debug("encoder pipe write failed");}}}
