#include "direct_mode.h"
#include <openvr_driver.h>
#include <algorithm>
#include <cstring>
#include <memory>
#include <string>

static std::string setting(const char *key,const char *fallback){char v[512]={};vr::VRSettings()->GetString("driver_svrt",key,v,sizeof(v));return v[0]?v:fallback;}
class SvrtHmd final:public vr::ITrackedDeviceServerDriver,public vr::IVRDisplayComponent{
 public:
  SvrtHmd():serial_(setting("serial_number","SVRT-PI4-001")){} const char *serial()const{return serial_.c_str();}
  vr::EVRInitError Activate(uint32_t id)override{id_=id;auto p=vr::VRProperties()->TrackedDeviceToPropertyContainer(id);vr::VRProperties()->SetStringProperty(p,vr::Prop_ModelNumber_String,setting("model_number","SVRT Wi-Fi HMD").c_str());vr::VRProperties()->SetStringProperty(p,vr::Prop_ManufacturerName_String,"SVRT");vr::VRProperties()->SetBoolProperty(p,vr::Prop_IsOnDesktop_Bool,false);vr::VRProperties()->SetBoolProperty(p,vr::Prop_HasDriverDirectModeComponent_Bool,true);vr::VRProperties()->SetFloatProperty(p,vr::Prop_DisplayFrequency_Float,(float)fps());vr::VRProperties()->SetFloatProperty(p,vr::Prop_SecondsFromVsyncToPhotons_Float,.020f);direct_.Start(setting("receiver_host","ROOT.local"),(uint16_t)vr::VRSettings()->GetInt32("driver_svrt","receiver_port"),fps(),(unsigned)vr::VRSettings()->GetInt32("driver_svrt","bitrate_mbps"),setting("ffmpeg_path","ffmpeg.exe"),setting("encoder","hevc_nvenc"));return vr::VRInitError_None;}
  void Deactivate()override{direct_.Stop();id_=vr::k_unTrackedDeviceIndexInvalid;}void EnterStandby()override{}void *GetComponent(const char *v)override{if(!strcmp(v,vr::IVRDisplayComponent_Version))return static_cast<vr::IVRDisplayComponent*>(this);if(!strcmp(v,vr::IVRDriverDirectModeComponent_Version))return static_cast<vr::IVRDriverDirectModeComponent*>(&direct_);return nullptr;}void DebugRequest(const char*,char*out,uint32_t n)override{if(n)out[0]=0;}
  vr::DriverPose_t GetPose()override{vr::DriverPose_t p{};p.qWorldFromDriverRotation.w=p.qDriverFromHeadRotation.w=p.qRotation.w=1;p.poseIsValid=p.deviceIsConnected=true;p.result=vr::TrackingResult_Running_OK;p.shouldApplyHeadModel=true;return p;}void RunFrame(){if(id_!=vr::k_unTrackedDeviceIndexInvalid)vr::VRServerDriverHost()->TrackedDevicePoseUpdated(id_,GetPose(),sizeof(vr::DriverPose_t));}
  void GetWindowBounds(int32_t*x,int32_t*y,uint32_t*w,uint32_t*h)override{*x=*y=0;*w=eye_width()*2;*h=eye_height();}bool IsDisplayOnDesktop()override{return false;}bool IsDisplayRealDisplay()override{return false;}void GetRecommendedRenderTargetSize(uint32_t*w,uint32_t*h)override{*w=eye_width();*h=eye_height();}void GetEyeOutputViewport(vr::EVREye e,uint32_t*x,uint32_t*y,uint32_t*w,uint32_t*h)override{*x=e==vr::Eye_Left?0:eye_width();*y=0;*w=eye_width();*h=eye_height();}void GetProjectionRaw(vr::EVREye,float*l,float*r,float*t,float*b)override{*l=-1;*r=1;*t=-1;*b=1;}vr::DistortionCoordinates_t ComputeDistortion(vr::EVREye,float u,float v)override{vr::DistortionCoordinates_t d{};d.rfRed[0]=d.rfGreen[0]=d.rfBlue[0]=u;d.rfRed[1]=d.rfGreen[1]=d.rfBlue[1]=v;return d;}bool ComputeInverseDistortion(vr::HmdVector2_t*,vr::EVREye,uint32_t,float,float)override{return false;}
 private:unsigned eye_width()const{int v=vr::VRSettings()->GetInt32("driver_svrt","render_width");return v>0?(unsigned)v:1440;}unsigned eye_height()const{int v=vr::VRSettings()->GetInt32("driver_svrt","render_height");return v>0?(unsigned)v:1600;}unsigned fps()const{int v=vr::VRSettings()->GetInt32("driver_svrt","display_frequency");return v>0?(unsigned)v:60;}uint32_t id_=vr::k_unTrackedDeviceIndexInvalid;std::string serial_;SvrtDirectMode direct_;
};
class Provider final:public vr::IServerTrackedDeviceProvider{public:vr::EVRInitError Init(vr::IVRDriverContext*c)override{VR_INIT_SERVER_DRIVER_CONTEXT(c);h_=std::make_unique<SvrtHmd>();return vr::VRServerDriverHost()->TrackedDeviceAdded(h_->serial(),vr::TrackedDeviceClass_HMD,h_.get())?vr::VRInitError_None:vr::VRInitError_Driver_Unknown;}void Cleanup()override{h_.reset();}const char*const*GetInterfaceVersions()override{return vr::k_InterfaceVersions;}void RunFrame()override{if(h_)h_->RunFrame();}bool ShouldBlockStandbyMode()override{return false;}void EnterStandby()override{}void LeaveStandby()override{}private:std::unique_ptr<SvrtHmd>h_;};static Provider provider;
extern "C" __declspec(dllexport) void *HmdDriverFactory(const char*n,int*e){if(!strcmp(n,vr::IServerTrackedDeviceProvider_Version))return &provider;if(e)*e=vr::VRInitError_Init_InterfaceNotFound;return nullptr;}
