find_package(PkgConfig QUIET)
pkg_check_modules(PC_DRM QUIET libdrm)
find_path(DRM_INCLUDE_DIR xf86drm.h HINTS ${PC_DRM_INCLUDE_DIRS})
find_library(DRM_LIBRARY NAMES drm HINTS ${PC_DRM_LIBRARY_DIRS})
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(DRM REQUIRED_VARS DRM_LIBRARY DRM_INCLUDE_DIR)
if(DRM_FOUND AND NOT TARGET DRM::DRM)
  add_library(DRM::DRM UNKNOWN IMPORTED)
  set_target_properties(DRM::DRM PROPERTIES IMPORTED_LOCATION "${DRM_LIBRARY}" INTERFACE_INCLUDE_DIRECTORIES "${DRM_INCLUDE_DIR}")
endif()
