find_package(PkgConfig REQUIRED)
set(FFmpeg_LIBRARIES "")
foreach(component IN LISTS FFmpeg_FIND_COMPONENTS)
  pkg_check_modules(PC_FFmpeg_${component} QUIET lib${component})
  find_path(FFmpeg_${component}_INCLUDE_DIR lib${component}/${component}.h HINTS ${PC_FFmpeg_${component}_INCLUDE_DIRS})
  find_library(FFmpeg_${component}_LIBRARY NAMES ${component} HINTS ${PC_FFmpeg_${component}_LIBRARY_DIRS})
  if(FFmpeg_${component}_INCLUDE_DIR AND FFmpeg_${component}_LIBRARY)
    set(FFmpeg_${component}_FOUND TRUE)
    add_library(FFmpeg::${component} UNKNOWN IMPORTED)
    set_target_properties(FFmpeg::${component} PROPERTIES IMPORTED_LOCATION "${FFmpeg_${component}_LIBRARY}" INTERFACE_INCLUDE_DIRECTORIES "${FFmpeg_${component}_INCLUDE_DIR}")
    list(APPEND FFmpeg_LIBRARIES "${FFmpeg_${component}_LIBRARY}")
  endif()
endforeach()
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(FFmpeg HANDLE_COMPONENTS REQUIRED_VARS FFmpeg_LIBRARIES)
