if(NOT UNIX)
  return()
endif()
find_package(PkgConfig REQUIRED)
pkg_check_modules(SVRT_PIPE_AV REQUIRED IMPORTED_TARGET libavformat libavcodec libavutil)
add_library(svrtpipe STATIC src/pipe.c)
add_library(svrt::pipe ALIAS svrtpipe)
target_compile_features(svrtpipe PUBLIC c_std_11)
target_include_directories(svrtpipe PUBLIC include)
target_link_libraries(svrtpipe PUBLIC PkgConfig::SVRT_PIPE_AV)
if(SVRT_BUILD_TESTS)
  add_executable(svrt-pipe-test tests/pipe_test.c)
  target_link_libraries(svrt-pipe-test PRIVATE svrt::pipe)
  add_test(NAME pipe-url COMMAND svrt-pipe-test)
endif()
